baseURL: "http://example.org/"
languageCode: "ja-jp"
title: 45歳ゼロから始める資産形成
contentDir: "content"
publishDir: "public"
hasCJKLanguage: true

copyright: "(c) 2022-{year} Shimarisu Taro"

disableKinds:
  - "RSS"

permalinks:
  life: /life/:year:month:day/
  invest: /invest/:year:month:day/
  blog: /blog/:year:month:day/
  tags: /tag/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: rrt
    tabWidth: 2

taxonomies:
  tag: tags
