title: "NoCC: メール"

baseURL: https://example.org/
languageCode: "ja-jp"
params:
  copyright: "© 2025 Hrapeco Club"
  author: "Harapeco Club"
  description: "個人情報の漏洩を防止する CC: のないメールクライアント"
  featured_image:
    path: "/images/cover/cover-2400x600.jpg"

theme: nocc
