title: "NoCC: メール"
theme: nocc

baseURL: https://example.org/
languageCode: "ja-jp"
params:
  copyright: "© 2025 Hrapeco Club"
  author: "Harapeco Club"
  description: "✅電子メールの誤送信による個人情報の漏洩を防ぐ"
  featured_image:
    path: "/images/cover/cover-2812x1875.jpg"
  search:
    name: "今月の情報漏洩事故"
    url: "https://www.google.com/search?q=CC+BCC+%E6%B5%81%E5%87%BA&sca_esv=a420dcef264fc5ad&source=lnt&tbs=qdr:m&sa=X&ved=2ahUKEwi2z5SptZeQAxVScvUHHfIBGHcQpwV6BAgHEA0&biw=1920&bih=991"

  editions:
    - slug: standard
      name: "スタンダード"
      price: "無料"
      features:
        smtp: true
        gmail: true
        sending: 20
        import: true
        export: true
        injection: true
        attachment: false
    - slug: premium
      name: "プレミアム"
      price: "10,000円"
      features:
        smtp: true
        gmail: true
        sending: 200
        import: true
        export: true
        injection: true
        attachment: true
  tools:
    - slug: application
      name: "メールソフト"
      logo: /images/comparison/mail-app.png
      cc: true
      server: SMTP
    - slug: nocc
      name: "NoCC:"
      logo: /images/comparison/NoCC.png
      cc: false
      server: SMTP/Gmail
    - slug: cloud
      name: "クラウドツール"
      logo: /images/comparison/cloud-tool.png
      cc: false
      server: Cloud

menus:
  main:
    - name: "NoCC:メール"
      pageRef: /
      weight: 10
    - name: "ダウンロード"
      pageRef: /download
      weight: 20
    - name: "使い方"
      pageRef: /howto
      weight: 30
    - name: "プレミアム"
      pageRef: /premium
      weight: 40

markup:
  goldmark:
    parser:
      attribute:
        block: true
        inline: true
