description: 45歳ゼロから始める資産形成
analytics_id: "G-RMRP0JXDEN"

author:
  companyname: "おなかをすかせた"
  name: "しまりすたろう"
  tags:
    - アスペルガー症候群
    - 注意欠陥多動性障害
    - 双極性障害
    - 睡眠障害
    - 睡眠時無呼吸症候群
    - 過敏性腸症候群
    - 低体温（34.6℃）
    - 企図振戦
    - 慢性咳嗽
    - 甲状腺腫（良性・手術済）
    - 自動車運転禁止
    - おくすり20種類
    - 血圧安定
    - 在宅勤務
    - キャパ少し余裕あり
    - 彼女が尊い
